version: '3'
services:
  mariadb:
    image: 'mariadb'
    ports:
      - '3306:3306' 
    environment:
      - 'MYSQL_ROOT_PASSWORD=mysqlAdmin123'
  
  contacts:
    image: 'dlwhitehurst/contacts'
    links:
      - mariadb
    depends_on:
      - mariadb
    ports:
      - '3000:3000'

